apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: {{ .CAData }}
    server: {{ .Server }}
  name: kubeapply-cluster
contexts:
- context:
  name: default-context
  context:
    cluster: kubeapply-cluster
    user: terraform-user
current-context: default-context
users:
- name: terraform-user
  user:
    token: {{ .Token }}
